# tasks file for user
---
- name: users | add / delete
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid | default(omit) }}"
    comment: "{{ item.comment | default('') }}"
    group: "{{ item.group | default(item.name) }}"
    groups: "{{ item.groups | default([]) | join(',') }}"
    append: "{{ item.append | default(false) }}"
    password: "{{ item.password | default('*') }}"
    update_password: "{{ item.update_password | default('always') }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    home: "{{ item.home | default(('/' if item.name == 'root' else '/home/') + item.name) }}"
    system: "{{ item.system | default(false) }}"
    state: "{{ item.state | default('present') }}"
    remove: "{{ item.remove | default(false) }}"
  with_items: "{{ user_users }}"
  tags:
    - user-users-gid

- name: users | permissions
  file:
    path: "{{ item.home | default(('/' if item.name == 'root' else '/home/') + item.name) }}"
    mode: "{{ item.dir_mode }}"
    state: directory
  when:
    - item.state | default('present') == 'present'
    - item.dir_mode is defined
  with_items: "{{ user_users }}"
  tags:
    - user-users-no-gid
